# Generated by Django 6.0.4 on 2026-05-03 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque_inteligente', '0003_alter_relatorioestoque_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemestoque',
            options={'ordering': ['conta_codigo', 'numero_item']},
        ),
        migrations.AddField(
            model_name='itemestoque',
            name='conta_codigo',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='itemestoque',
            name='conta_descricao',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
