# Generated by Django 6.0.4 on 2026-05-02 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque_inteligente', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='relatorioestoque',
            name='texto_extraido',
            field=models.TextField(blank=True, default=''),
        ),
    ]
