# Generated by Django 6.0.4 on 2026-05-02 21:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque_inteligente', '0002_relatorioestoque_texto_extraido'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='relatorioestoque',
            options={},
        ),
        migrations.RenameField(
            model_name='relatorioestoque',
            old_name='criado_em',
            new_name='data_envio',
        ),
        migrations.AlterField(
            model_name='relatorioestoque',
            name='nome_original',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='relatorioestoque',
            name='texto_extraido',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='ItemEstoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_item', models.PositiveIntegerField()),
                ('codigo_material', models.CharField(max_length=20)),
                ('descricao', models.TextField()),
                ('unidade_medida', models.CharField(blank=True, max_length=20)),
                ('finalidade_compra', models.CharField(blank=True, max_length=100)),
                ('cmm', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('ce', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('estoque', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('preco_medio', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('valor', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('status', models.CharField(choices=[('CRITICO', 'Crítico'), ('ATENCAO', 'Atenção'), ('NORMAL', 'Normal'), ('SEM_MOVIMENTO', 'Sem movimento'), ('ESTOQUE_PARADO', 'Estoque parado')], default='SEM_MOVIMENTO', max_length=30)),
                ('quantidade_sugerida', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('relatorio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='estoque_inteligente.relatorioestoque')),
            ],
            options={
                'ordering': ['numero_item'],
            },
        ),
    ]
