# Generated by Django 6.0.4 on 2026-05-04 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque_inteligente', '0004_alter_itemestoque_options_itemestoque_conta_codigo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='relatorioestoque',
            name='hash_arquivo',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
    ]
