# Generated by Django 6.0.4 on 2026-05-04 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque_inteligente', '0005_relatorioestoque_hash_arquivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemestoque',
            name='ativo',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='itemestoque',
            name='conta_codigo',
            field=models.CharField(blank=True, db_index=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='itemestoque',
            name='status',
            field=models.CharField(choices=[('CRITICO', 'Crítico'), ('ATENCAO', 'Atenção'), ('NORMAL', 'Normal'), ('SEM_MOVIMENTO', 'Sem movimento'), ('ESTOQUE_PARADO', 'Estoque parado')], db_index=True, default='SEM_MOVIMENTO', max_length=30),
        ),
    ]
